### ISSUE TITLE
Request: include a view/controller/service generator for angular.

### ISSUE THREAD

**Issue by adityamenon** [endorama/generator-langular#4]
Hello, would be cool if there were simple commands one could run to generate the various files and include them automagically into the index.html file. A lot of tedium would be saved.

**Comment by endorama** [comment]
Sorry for this late late late reply :( I stopped using Laravel and hadn't too much time to look into this.

I thought about a solution like the one you mention, but is a lot of effort to implement and [seeing this](http://www.dancancro.com/comparison-of-angularjs-application-starters/) ( there are a hundred of angular generator in the wild ) I don't think is wise idea.

Probably the most profitable solution is to use this generator for a simple folder's structure and then use a   standard/more known generator to manage files.

Sorry again for the reply lateness

**Comment by adityamenon** [comment]
Cool, thanks for the reply anyway :-)
